
custom_messages={"user_register_success": 1,
                "verify_mail_success": 2,
                'login_success': 3,
                'request_pw_resset_success':4,
                'pw_token_check_success':5,
                'set_new_pw_success':6,
                'add_idea':7,
                'user_comment':8,
                'user_feedback':9,
                'user_register_failure':10,
                'verify_mail_link_expired':11,
                'verify_mail_invalid_token':12,
                'login_invalid_credentials':13,
                "request_pw_resset_email_not_found":14,
                'pw_resset_token_invalid':15}