# Generated by Django 2.2.27 on 2022-05-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animation_allstars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='like',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='animation_allstars.IdeaFeedback'),
        ),
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
