# Generated by Django 2.2.27 on 2022-05-15 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation_allstars', '0003_auto_20220516_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='likes',
        ),
        migrations.AddField(
            model_name='ideafeedback',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
